import { useEffect, useState } from "react";
import { ArrowRight, ChevronDown, Gem, HeartHandshake, ShieldCheck, Sparkles } from "lucide-react";
import Container from "@/components/common/Container/Container";
import SectionHeading from "@/components/common/SectionHeading/SectionHeading";
import Button from "@/components/common/Button/Button";
import ProductGrid from "@/components/home/ProductGrid";
import Seo from "@/components/Seo";
import { productService } from "@/services/product.service";

const values = [[Gem, "Artistry that endures", "Pieces selected for their craft, detail and timeless presence."], [ShieldCheck, "Quality assured", "Every order is carefully checked before it leaves our atelier."], [HeartHandshake, "Personal guidance", "Thoughtful styling support for every bridal vision."]];
const faqs = ["How long will my order take?", "Can I request help choosing my bridal set?", "Do you ship across India?"];
const getItems = (data) => Array.isArray(data) ? data : data?.products ?? data?.categories ?? [];

function Home() {
  const [categories, setCategories] = useState([]); const [featured, setFeatured] = useState([]); const [latest, setLatest] = useState([]); const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; Promise.allSettled([productService.getCategories(), productService.getFeatured(), productService.getLatest()]).then(([categoryResult, featuredResult, latestResult]) => { if (!active) return; if (categoryResult.status === "fulfilled") setCategories(getItems(categoryResult.value)); if (featuredResult.status === "fulfilled") setFeatured(getItems(featuredResult.value)); if (latestResult.status === "fulfilled") setLatest(getItems(latestResult.value)); }).finally(() => active && setLoading(false)); return () => { active = false; }; }, []);
  return <><Seo title="Royal Bridal | Jewellery for your forever moment" description="Discover bridal jewellery selected for every celebration." />
    <section className="overflow-hidden bg-[#f5ede5]"><Container className="grid min-h-[580px] items-center gap-12 py-14 md:grid-cols-2 md:py-18"><div><p className="text-xs font-bold uppercase tracking-[.28em] text-[#9b6b35]">The bridal edit</p><h1 className="mt-5 max-w-xl font-serif text-5xl leading-[.98] text-[#24181a] sm:text-6xl lg:text-7xl">Jewellery for your <em className="font-light">forever</em> moment.</h1><p className="mt-6 max-w-md text-base leading-7 text-stone-600">A considered collection of bridal adornments, made to complete the day you have always imagined.</p><Button className="mt-8" onClick={() => document.getElementById("featured")?.scrollIntoView()}>Explore the collection <ArrowRight size={16} /></Button></div><div className="relative mx-auto aspect-[4/5] w-full max-w-md overflow-hidden bg-[#7d2034]"><div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,#e6bf80_0%,#b8754d_20%,transparent_21%),radial-gradient(ellipse_at_center,#e6bf80_0%,#b8754d_20%,transparent_21%),radial-gradient(ellipse_at_center,#e6bf80_0%,#b8754d_20%,transparent_21%)] bg-[size:45%_45%,30%_30%,25%_25%] bg-[position:20%_20%,78%_60%,20%_85%] bg-no-repeat opacity-80" /><p className="absolute bottom-7 left-7 max-w-[11rem] font-serif text-2xl leading-tight text-white">For the story only you can tell.</p></div></Container></section>
    <section className="py-18"><Container><SectionHeading eyebrow="Made for every ritual" title="Discover your bridal expression" /><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{categories.slice(0, 4).map((category, index) => <a href={`/products?category=${category.slug}`} key={category.id} className="group relative aspect-[4/5] overflow-hidden bg-[#d9bea5]"><div className={`absolute inset-0 opacity-80 ${index % 2 ? "bg-[#a64d49]" : "bg-[#7d2034]"}`} />{category.image && <img src={category.image} alt="" loading="lazy" className="absolute inset-0 h-full w-full object-cover mix-blend-multiply" />}<div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/60 p-5 text-white"><p className="font-serif text-xl">{category.name}</p><span className="mt-2 inline-flex items-center gap-1 text-xs uppercase tracking-widest opacity-0 transition group-hover:opacity-100">Explore <ArrowRight size={13} /></span></div></a>)}</div>{!loading && categories.length === 0 && <p className="mt-5 text-center text-sm text-stone-500">Collections will appear here soon.</p>}</Container></section>
    <section id="featured" className="bg-[#fbf8f5] py-18"><Container><SectionHeading eyebrow="Our signatures" title="Featured treasures" description="Handpicked pieces for the bride who makes tradition her own." /><ProductGrid products={featured} loading={loading} /></Container></section>
    <section className="py-18"><Container><SectionHeading eyebrow="Just arrived" title="New in the collection" /><ProductGrid products={latest} loading={loading} /></Container></section>
    <section className="bg-[#24181a] py-18 text-white"><Container><SectionHeading eyebrow="The Royal Bridal promise" title="A beautiful beginning, thoughtfully considered" /><div className="grid gap-8 md:grid-cols-3">{values.map(([Icon, title, text]) => <div key={title} className="border-t border-white/25 pt-6"><Icon className="text-[#d5aa65]" /><h3 className="mt-5 font-serif text-2xl">{title}</h3><p className="mt-3 text-sm leading-6 text-stone-300">{text}</p></div>)}</div></Container></section>
    <section className="py-18"><Container className="grid gap-10 md:grid-cols-2"><div><SectionHeading eyebrow="A celebration, curated" title="Your bridal journey, beautifully simplified" align="left" /><ol className="space-y-5">{["Share your vision", "Explore a tailored edit", "Receive your finishing touch"].map((step, index) => <li className="flex gap-4" key={step}><span className="font-serif text-3xl text-[#9b6b35]">0{index + 1}</span><p className="pt-1.5 text-stone-700">{step}</p></li>)}</ol></div><div className="bg-[#e6d2bf] p-8 sm:p-12"><Sparkles className="text-[#7d2034]" /><blockquote className="mt-8 font-serif text-3xl leading-tight text-[#24181a]">“Every detail felt like it had been chosen just for me.”</blockquote><p className="mt-6 text-sm font-semibold uppercase tracking-widest text-[#7d2034]">— A Royal Bride</p></div></Container></section>
    <section className="bg-[#f5ede5] py-18"><Container><SectionHeading eyebrow="Frequently asked" title="Everything you need to know" /> <div className="mx-auto max-w-3xl divide-y divide-stone-300">{faqs.map((faq) => <details className="group py-5" key={faq}><summary className="flex cursor-pointer list-none items-center justify-between font-medium text-stone-800">{faq}<ChevronDown className="transition group-open:rotate-180" size={19} /></summary><p className="mt-3 max-w-xl text-sm leading-6 text-stone-600">Our bridal concierge is here to help. Contact us and we’ll share the details you need for your selection.</p></details>)}</div></Container></section>
    <section className="py-18"><Container><div className="bg-[#7d2034] px-6 py-12 text-center text-white sm:px-12"><p className="text-xs font-bold uppercase tracking-[.28em] text-[#e6c98c]">Keep in touch</p><h2 className="mt-4 font-serif text-3xl">A little bridal inspiration, delivered.</h2><form className="mx-auto mt-7 flex max-w-md flex-col gap-3 sm:flex-row"><label className="sr-only" htmlFor="newsletter">Email address</label><input id="newsletter" type="email" required placeholder="Your email address" className="min-w-0 flex-1 rounded-full bg-white px-5 py-3 text-sm text-stone-800 outline-none" /><Button type="submit" className="bg-[#d5aa65] hover:bg-[#c49650]">Subscribe</Button></form></div></Container></section>
  </>;
}

export default Home;
