import compression from 'compression';
import cors from 'cors';
import express from 'express';
import helmet from 'helmet';
import morgan from 'morgan';
import cookieParser from 'cookie-parser';
import { env } from './config/env.js';
import { errorHandler, notFound } from './middlewares/error.middleware.js';
import { apiRateLimiter } from './middlewares/rate-limit.middleware.js';
import { requestId } from './middlewares/request-id.middleware.js';
import { requestLogger } from './middlewares/request-logger.middleware.js';
import healthRouter from './routes/health.routes.js';
import adminAuthRouter from './routes/admin-auth.routes.js';
import { categories, products } from './routes/catalog.routes.js';
import docsRouter from './routes/docs.routes.js';
import orderRouter from './routes/order.routes.js';
import checkoutRouter from './routes/checkout.routes.js';
import paymentRouter from './routes/payment.routes.js';
import customerRouter from './routes/customer.routes.js'; import dashboardRouter from './routes/dashboard.routes.js';
import uploadRouter from './routes/upload.routes.js';

export const app = express();

app.set('trust proxy', 1);
app.use(helmet());
app.use(requestId);
app.use(requestLogger);
app.post('/api/payments/webhook', express.raw({ type: 'application/json' }));
app.use(cors({ origin: env.clientUrl, credentials: true }));
app.use(compression());
app.use(express.json({ limit: '1mb' }));
app.use(express.urlencoded({ extended: true, limit: '1mb' }));
app.use(cookieParser());
app.use(morgan(env.nodeEnv === 'production' ? 'combined' : 'dev'));
app.use('/api', apiRateLimiter);
app.use('/api/health', healthRouter);
app.use('/api/admin', adminAuthRouter);
app.use('/api/categories', categories);
app.use('/api/products', products);
app.use('/api/docs', docsRouter);
app.use('/api/orders', orderRouter);
app.use('/api/checkout', checkoutRouter);
app.use('/api/payments', paymentRouter);
app.use('/api/customers', customerRouter); app.use('/api/dashboard', dashboardRouter);
app.use('/api/uploads', uploadRouter);
app.use(notFound);
app.use(errorHandler);
